name: deniz_lib
description: A starting point for Dart libraries or applications.
version: 0.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.2
  device_info_plus: ^8.1.0
  window_manager: ^0.3.1
  url_launcher: ^6.1.10
  fluttertoast: ^8.2.1
  page_transition: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^2.0.0
  test: ^1.16.0
  flutter_lints: ^2.0.0
  # change_app_package_name: ^1.1.0
